%% beamforming.m
% =========================================================================
% Generate ULA Hybrid Beamforming pattern lookup table for ns-3 (uav-to-leo.cc)
%
% Architecture:
%   - 10 steering sectors:    theta_s = 0, 10, 20, ..., 90 degrees
%   - 901 observation angles: theta   = 0.0, 0.1, ..., 90.0 degrees per sector
%   - Total: 10 x 901 = 9010 entries
%
% Output: beam_pattern.csv with columns
%           steering_deg, elevation_deg, gain_dB
%
% Lookup workflow in ns-3:
%   1. Round actual elevation to nearest 10 deg -> select steering sector
%      (e.g., elev = 78.6 deg -> use steering theta_s = 80 deg pattern)
%   2. Within that sector's pattern, look up exact elevation (0.1 deg resolution)
%      (e.g., key = round(78.6 * 10) = 786)
%
% This is the "steered ULA" model. The previous version computed only the
% un-steered (broadside) array factor, which gave negative gains at all
% elevations and INCORRECTLY DEGRADED the SNR. The current model:
%   - Steers the main lobe toward the target direction
%   - Peak gain ~ 10*log10(N) dB at steered direction
%   - Includes element pattern (zenith-pointing taper)
%   - Includes hybrid BF efficiency loss
% =========================================================================

clear; close all; clc;

%% ====================== Parameters ======================
N             = 16;       % Total antenna elements (Hybrid BF total antennas)
N_RF          = 4;        % Number of RF chains (Hybrid BF)
freq_GHz      = 13.5;     % Carrier frequency (Ku-User band default)
d_over_lambda = 0.5;      % Element spacing in wavelengths (lambda/2)

% Hybrid efficiency loss in dB (negative number)
%   - Phase Shifter (PS) quantization: ~ -0.5 dB
%   - RF combiner / power splitter loss: ~ -0.5 dB
%   - Sub-array architecture limitation: ~ -0.5 dB
%   Typical total: -1.5 dB
eta_hybrid_dB = -1.5;

% Single-element directivity peak (dBi over isotropic)
%   - Patch antenna: typically 5-7 dBi
%   - Dipole:        2.15 dBi
G_elem_max_dB = 5.0;

%% ============== Steering & observation grids ============
steering_angles_deg    = 0:10:90;       % 10 steering sectors (centered)
observation_angles_deg = 0:0.1:90;      % 901 points per sector (0.1 deg res)

nSteer = length(steering_angles_deg);
nObs   = length(observation_angles_deg);

fprintf('=== Hybrid ULA Beamforming Generator ===\n');
fprintf('  N         = %d antennas\n', N);
fprintf('  N_RF      = %d RF chains\n', N_RF);
fprintf('  freq      = %.2f GHz (lambda = %.2f mm)\n', freq_GHz, 300/freq_GHz);
fprintf('  d/lambda  = %.2f\n', d_over_lambda);
fprintf('  Steering  = %d sectors (every 10 deg)\n', nSteer);
fprintf('  Obs ang   = %d points (0.1 deg res)\n', nObs);
fprintf('  Total     = %d entries\n\n', nSteer * nObs);

%% ============== Compute beam pattern ====================
results = zeros(nSteer * nObs, 3);   % [steering_deg, elev_deg, gain_dB]
row = 1;

for s_idx = 1:nSteer
    theta_s = steering_angles_deg(s_idx);
    sin_s   = sind(theta_s);
    
    for o_idx = 1:nObs
        theta = observation_angles_deg(o_idx);
        
        % ---- Array Factor for steered ULA ----
        % psi = 2*pi*(d/lambda)*(sin(theta) - sin(theta_s))
        % |AF| = | sin(N*psi/2) / sin(psi/2) |   (closed form)
        % Peak |AF| = N at theta = theta_s
        psi = 2 * pi * d_over_lambda * (sind(theta) - sin_s);
        
        if abs(sin(psi/2)) < 1e-12
            AF_mag = N;                                   % L'Hopital: peak case
        else
            AF_mag = abs(sin(N*psi/2) / sin(psi/2));
        end
        
        % Array gain (dB) over single element:
        %   G_AF = |AF|^2 / N   ->   peak = N -> 10*log10(N)
        G_AF_dB = 20*log10(max(AF_mag, 1e-6)) - 10*log10(N);
        
        % ---- Element pattern (zenith-pointing taper) ----
        % Each antenna element has its own directivity, peaking at zenith.
        % Modeled as G_elem(theta) = G_elem_max + 20*log10(sin(theta))
        sin_elev = max(sind(theta), 1e-3);
        G_elem_dB = G_elem_max_dB + 20*log10(sin_elev);
        
        % ---- Total gain (with hybrid efficiency loss) ----
        G_total_dB = G_AF_dB + G_elem_dB + eta_hybrid_dB;
        G_total_dB = max(G_total_dB, -50);                % floor at -50 dB
        
        results(row, :) = [theta_s, theta, G_total_dB];
        row = row + 1;
    end
end

%% ============== Write CSV ===============================
filename = 'beam_pattern.csv';
fid = fopen(filename, 'w');
fprintf(fid, '# Generated by beamforming.m\n');
fprintf(fid, '# nAnt=%d, nRF=%d, freq=%.1fGHz, d=%.2f*lambda, hybrid_loss=%.1fdB\n', ...
        N, N_RF, freq_GHz, d_over_lambda, eta_hybrid_dB);
fprintf(fid, 'steering_deg,elevation_deg,gain_dB\n');
for i = 1:size(results, 1)
    fprintf(fid, '%.0f,%.1f,%.4f\n', results(i,1), results(i,2), results(i,3));
end
fclose(fid);
fprintf('Wrote %s (%d rows, ~%.0f KB)\n\n', ...
        filename, size(results,1), 0.001*size(results,1)*22);

%% ============== Sanity checks ===========================
fprintf('=== Peak gain verification (should be near %.1f dB) ===\n', ...
        10*log10(N) + G_elem_max_dB + eta_hybrid_dB);
fprintf('  Theoretical peak: 10*log10(%d) + %.1f + (%.1f) = %.2f dB\n', ...
        N, G_elem_max_dB, eta_hybrid_dB, ...
        10*log10(N) + G_elem_max_dB + eta_hybrid_dB);
fprintf('\n  Steering   Peak elev   Peak gain (dB)\n');
fprintf('  --------   ---------   --------------\n');
for s_idx = 1:nSteer
    theta_s = steering_angles_deg(s_idx);
    mask = (results(:,1) == theta_s);
    sub  = results(mask, :);
    [peak_dB, peak_idx] = max(sub(:,3));
    fprintf('   %2d deg     %5.1f deg     %6.2f\n', ...
            theta_s, sub(peak_idx,2), peak_dB);
end

%% ============== Visualization ===========================
% Plot 1: linear-scale beam patterns vs observation angle
figure('Position', [100 100 1000 600]);
hold on; grid on;
colors = jet(nSteer);
for s_idx = 1:nSteer
    theta_s = steering_angles_deg(s_idx);
    mask = results(:,1) == theta_s;
    plot(results(mask,2), results(mask,3), ...
         'Color', colors(s_idx,:), ...
         'LineWidth', 1.4, ...
         'DisplayName', sprintf('\\theta_s = %d^\\circ', theta_s));
end
xlabel('Observation Elevation (deg)', 'FontSize', 12);
ylabel('Total Gain (dB)', 'FontSize', 12);
title(sprintf(['ULA Hybrid Beamforming Pattern  ' ...
               '(N=%d, N_{RF}=%d, f=%.1f GHz, d=\\lambda/2)'], ...
              N, N_RF, freq_GHz), 'FontSize', 13);
legend('Location', 'southwest', 'NumColumns', 2);
ylim([-30 20]);
xlim([0 90]);
saveas(gcf, 'beam_pattern_cartesian.png');
fprintf('\nSaved: beam_pattern_cartesian.png\n');

% Plot 2: polar plots for selected steering angles
figure('Position', [100 100 1000 600]);
selected_steerings = [0 30 60 90];
for k = 1:length(selected_steerings)
    theta_s = selected_steerings(k);
    mask = results(:,1) == theta_s;
    sub  = results(mask, :);
    
    subplot(2, 2, k);
    % Convert to polar: angle in degrees -> theta in polar plot
    % We want elevation 0 = horizon, 90 = zenith
    % Map: polar_angle = 90 - elevation, so zenith is up
    polar_ang_rad = (90 - sub(:,2)) * pi/180;
    gain_lin = max(sub(:,3) + 30, 0);   % offset to make positive for polar
    polarplot(polar_ang_rad, gain_lin, 'b-', 'LineWidth', 1.3);
    hold on;
    polarplot([(90 - theta_s)*pi/180 (90 - theta_s)*pi/180], ...
              [0 max(gain_lin)], 'r--', 'LineWidth', 1.5);
    title(sprintf('Steering \\theta_s = %d^\\circ', theta_s), 'FontSize', 11);
    rticks([10 20 30 40]);
    rticklabels({'-20', '-10', '0', '+10'});
    thetalim([0 90]); thetaticks(0:15:90);
    thetaticklabels({'90', '75', '60', '45', '30', '15', '0'});
end
sgtitle('Polar Beam Patterns (radial scale = gain in dB + 30)', 'FontSize', 12);
saveas(gcf, 'beam_pattern_polar.png');
fprintf('Saved: beam_pattern_polar.png\n');

fprintf('\n=== Done. Copy beam_pattern.csv to:\n');
fprintf('    ns-3.35/contrib/leo/examples/beam_pattern.csv\n');
fprintf('=== Run ns-3 with:\n');
fprintf('    ./waf --run "uav-to-leo --bpFile=contrib/leo/examples/beam_pattern.csv"\n');
